// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:75d7f769-df7d-4d65-8e15-564a09200109",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vg6t3Sd5w",
    "aws_user_pools_web_client_id": "368ibduk8hja6fj6vhspk6u3e",
    "aws_user_files_s3_bucket": "reactnativegraphql7168560b09ad443d8df8e41e271a8770",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4rngjmy2snbixmogtyhkjk2fjq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
